[package]
name = "atruct"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atruct_internal = { path = "../atruct_internal" }
quote = "1.0"
syn = "1.0"

[lib]
proc-macro = true